---
platform_upgrade_packages: true
forgejo_version: '15.0.9'
forgejo_checksums:
  x86_64: 04bf4981241cd7a39554809686d3e1811e219073cbf9a6ce6ed3895adfd8d17a
  aarch64: be0aff7570c0b94722b4fee01429eabe9991082590556f127a916e6cc8c92464
forgejo_architectures:
  x86_64: amd64
  aarch64: arm64
publish_interval: 60s
backup_retention_days: 7
backup_restic_repository: ''
# Accès automatique sans DNS à configurer.
ansible_user: root
forgejo_admin_user: docsadmin
forgejo_admin_email: '{{ platform_email }}'
certificate_email: '{{ platform_email }}'
knowledge_repo: base-connaissance
knowledge_branch: main
git_domain: '{{ ansible_host | default(inventory_hostname) }}'
docs_domain: '{{ ansible_host | default(inventory_hostname) }}'
git_https_port: '{{ 8443 if git_domain == docs_domain else 443 }}'
docs_https_port: 443
git_url: 'https://{{ git_domain }}{{ ":" ~ git_https_port if git_https_port | int != 443 else "" }}'
docs_url: 'https://{{ docs_domain }}{{ ":" ~ docs_https_port if docs_https_port | int != 443 else "" }}'
tls_mode: selfsigned
